# Generated by Django 5.2.12 on 2026-04-04 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstatusPruebas',
            fields=[
                ('IdEstatusPrueba', models.AutoField(primary_key=True, serialize=False)),
                ('NombreEstatusPrueba', models.CharField(max_length=30)),
                ('Activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='TiposPruebas',
            fields=[
                ('IdTipoPrueba', models.AutoField(primary_key=True, serialize=False)),
                ('NombreTipoPrueba', models.CharField(max_length=30)),
                ('Activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pruebas',
            fields=[
                ('IdPrueba', models.AutoField(primary_key=True, serialize=False)),
                ('CodigoPrueba', models.CharField(max_length=10)),
                ('NombrePrueba', models.CharField(max_length=50)),
                ('IdentificadorPrueba', models.CharField(max_length=30, null=True)),
                ('ComentariosPrueba', models.CharField(max_length=100)),
                ('FechaAlta', models.DateField()),
                ('FechaInicio', models.DateField()),
                ('FechaFin', models.DateField()),
                ('IdEstatusPrueba', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pruebas.estatuspruebas')),
                ('IdTester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.testers')),
                ('IdTipoPrueba', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pruebas.tipospruebas')),
            ],
        ),
    ]
