# Generated by Django 5.2.12 on 2026-04-05 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pruebas', '0002_alter_pruebas_comentariosprueba'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pruebas',
            name='FechaFin',
            field=models.DateField(null=True),
        ),
    ]
