# Generated by Django 5.2.12 on 2026-04-05 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pruebas', '0003_alter_pruebas_fechafin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pruebas',
            name='FechaInicio',
            field=models.DateField(null=True),
        ),
    ]
