# Generated by Django 5.2.12 on 2026-04-04 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Testers',
            fields=[
                ('IdTester', models.AutoField(primary_key=True, serialize=False)),
                ('NombreTester', models.CharField(max_length=30)),
                ('ApellidoPaterno', models.CharField(max_length=30)),
                ('ApellidoMaterno', models.CharField(max_length=30, null=True)),
                ('Activo', models.BooleanField(default=True)),
            ],
        ),
    ]
